In [6]:
import pandas as pd
import sqlite3
from urllib import request

In [8]:
course_data_url = 'https://raw.githubusercontent.com/rhodyprog4ds/rhodyds/main/data/'

In [10]:
df_18 = pd.read_csv(course_data_url+'2018-players.csv')
df_19 = pd.read_csv(course_data_url+'2019-players.csv')

In [11]:
df_18.head()

      TEAM_ID  PLAYER_ID  SEASON
0  1610612761     202695    2018
1  1610612761    1627783    2018
2  1610612761     201188    2018
3  1610612761     201980    2018
4  1610612761     200768    2018

In [14]:
df_19.head()

        PLAYER_NAME     TEAM_ID  PLAYER_ID  SEASON
0     Royce O'Neale  1610612762    1626220    2019
1  Bojan Bogdanovic  1610612762     202711    2019
2       Rudy Gobert  1610612762     203497    2019
3  Donovan Mitchell  1610612762    1628378    2019
4       Mike Conley  1610612762     201144    2019

In [17]:
df_18.shape, df_19.shape

((748, 3), (626, 4))

In [20]:
pd.concat([df_19,df_19])

          PLAYER_NAME     TEAM_ID  PLAYER_ID  SEASON
0       Royce O'Neale  1610612762    1626220    2019
1    Bojan Bogdanovic  1610612762     202711    2019
2         Rudy Gobert  1610612762     203497    2019
3    Donovan Mitchell  1610612762    1628378    2019
4         Mike Conley  1610612762     201144    2019
..                ...         ...        ...     ...
621   Anthony Bennett  1610612745     203461    2019
622      Ray Spalding  1610612737    1629034    2019
623      Devyn Marble  1610612744     203906    2019
624   Hassani Gravett  1610612753    1629755    2019
625     JaKeenan Gant  1610612754    1629721    2019

[1252 rows x 4 columns]

In [22]:
pd.concat([df_19,df_19]).head()

        PLAYER_NAME     TEAM_ID  PLAYER_ID  SEASON
0     Royce O'Neale  1610612762    1626220    2019
1  Bojan Bogdanovic  1610612762     202711    2019
2       Rudy Gobert  1610612762     203497    2019
3  Donovan Mitchell  1610612762    1628378    2019
4       Mike Conley  1610612762     201144    2019

In [26]:
request.urlretrieve('https://github.com/rhodyprog4ds/rhodyds/raw/main/data/nba1819.db',
      'nba1819.db')

('nba1819.db', <http.client.HTTPMessage at 0x127c156d0>)

In [28]:
conn = sqlite3.connect('nba1819.db')
cursor = conn.cursor()

In [30]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")

In [32]:
cursor.fetchall()

[('teams',),
 ('conferences',),
 ('playerGameStats2018',),
 ('playerGameStats2019',),
 ('teamGameStats2018',),
 ('teamGameStats2019',),
 ('playerTeams2018',),
 ('playerTeams2019',),
 ('teamDailyRankings2018',),
 ('teamDailyRankings2019',),
 ('playerNames',)]

In [34]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';",conn)

                     name
0                   teams
1             conferences
2     playerGameStats2018
3     playerGameStats2019
4       teamGameStats2018
5       teamGameStats2019
6         playerTeams2018
7         playerTeams2019
8   teamDailyRankings2018
9   teamDailyRankings2019
10            playerNames