In [2]:
import pandas as pd
import seaborn as sns

#make plots look nicer and increase font size
sns.set_theme(font_scale=2, palette='colorblind')

In [3]:
url_base = 'https://raw.githubusercontent.com/rhodyprog4ds/rhodyds/main/data/'

data_filename_list = ['study_a.csv','study_b.csv','study_c.csv']

In [4]:
example_data = {datafile.split('.')[0]: pd.read_csv(url_base+datafile) for datafile in data_filename_list}

In [5]:
example_data['study_a']

           name treatmenta  treatmentb
0    John Smith          -           2
1      Jane Doe         16          11
2  Mary Johnson          3           1

In [6]:
from IPython.display import display

In [7]:
[display(df) for df in example_data.values()];

           name treatmenta  treatmentb
0    John Smith          -           2
1      Jane Doe         16          11
2  Mary Johnson          3           1

  intervention John Smith  Jane Doe  Mary Johnson
0   treatmenta          -        16             3
1   treatmentb          2        11             1

         person treatment result
0    John Smith         a      -
1      Jane Doe         a     16
2  Mary Johnson         a      3
3    John Smith         b      2
4      Jane Doe         b     11
5  Mary Johnson         b      1

In [8]:
example_data['study_c'].describe()

            person treatment result
count            6         6      6
unique           3         2      6
top     John Smith         a      -
freq             2         3      1

In [9]:
example_data = {datafile.split('.')[0]:pd.read_csv(url_base+datafile,na_values='-') 
                for datafile in data_filename_list}

In [10]:
example_data['study_c'].groupby('person')['result'].mean()

person
Jane Doe        13.5
John Smith       2.0
Mary Johnson     2.0
Name: result, dtype: float64

In [33]:
df = example_data['study_a'].melt()

In [35]:
arabica_data_url = 'https://raw.githubusercontent.com/jldbc/coffee-quality-database/master/data/arabica_data_cleaned.csv'
# load the data
coffee_df = pd.read_csv(arabica_data_url)
# get total bags per country
bags_per_country = coffee_df.groupby('Country.of.Origin')['Number.of.Bags'].sum()

# sort descending, keep only the top 10 and pick out only the country names
top_bags_country_list = bags_per_country.sort_values(ascending=False)[:10].index

# filter the original data for only the countries in the top list
top_coffee_df = coffee_df[coffee_df['Country.of.Origin'].isin(top_bags_country_list)]

In [36]:
top_bags_country_list

Index(['Colombia', 'Guatemala', 'Brazil', 'Mexico', 'Honduras', 'Ethiopia',
       'Costa Rica', 'Nicaragua', 'El Salvador', 'Kenya'],
      dtype='object', name='Country.of.Origin')

In [40]:
value_vars = ['Aroma', 'Flavor', 'Aftertaste', 'Acidity', 'Body',
       'Balance', 'Uniformity', 'Clean.Cup', 'Sweetness', 'Cupper.Points',
       'Total.Cup.Points', 'Moisture']
id_vars = ['Species', 'Owner', 'Country.of.Origin']
coffee_tall = coffee_df.melt(id_vars=id_vars, value_vars=value_vars,
              var_name='rating')