## Title

In [3]:
!pip install xlrd

Requirement already satisfied: xlrd in /opt/anaconda3/lib/python3.12/site-packages (2.0.1)

In [4]:
import pandas as pd
import seaborn as sns
#import needed packages

In [5]:
data_file = 'https://nces.ed.gov/programs/digest/d19/tables/xls/tabn325.35.xls'

In [6]:
df = pd.read_excel(data_file)
# load in the data with default options to look at it

## Check the header and footer

In [8]:
df.head()

,"Table 325.35. Degrees in computer and information sciences conferred by postsecondary institutions, by \n level of degree and sex of student: 1970-71 through 2017-18",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Year,Bachelor's degrees,NaN,NaN,NaN,NaN,Master's degrees,NaN,NaN,Doctor's degrees,NaN,NaN
1,NaN,Total,NaN,Males,Females,Females as a percent of total,Total,Males,Females,Total,Males,Females
2,NaN,Number,Annual percent change,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2,3,4,5,6,7,8,9,10,11,12
4,1970-71 ..........................,2388,†,2064,324,13.567839,1588,1424,164,128,125,3

In [9]:
df.tail()

,"Table 325.35. Degrees in computer and information sciences conferred by postsecondary institutions, by \n level of degree and sex of student: 1970-71 through 2017-18",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
64,2012-13 to 2017-18 .........,56.193952,†,52.132588,74.909211,†,103.968045,89.836145,141.406375,9.97819,6.756757,23.446328
65,†Not applicable.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,#Rounds to zero.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NOTE: Data are for postsecondary institutions ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,"SOURCE: U.S. Department of Education, National...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- Are all of the rows data?
No. Some of the rows are NaN, some are notes and sources because it seems that pandas did not read in the file correctly. It seems like some other information got stored as part of the csv

- how many header rows are there?
11 header rows

- how many rows are summary data at the bottom?
3 of the bottom rows are summary data

Identify and apply the necessary changes to the read function to make the header easy to work with. Look at th docs for the read function. In particular look for paramters related to the header, footer, and skipping rows.

In [14]:
df = pd.read_excel(data_file, header=[1], skiprows=[0], skipfooter=4)

examine the dataset to confirm what you did worked, once it is good, save it to a variable

In [16]:
df.head()

,Unnamed: 0,Total,Unnamed: 2,Males,Females,Females as a percent of total,Total.1,Males.1,Females.1,Total.2,Males.2,Females.2
0,NaN,Number,Annual percent change,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,3,4,5,6,7,8,9,10,11,12
2,1970-71 ..........................,2388,†,2064,324,13.567839,1588,1424,164,128,125,3
3,1971-72 ..........................,3402,42.462312,2941,461,13.550852,1977,1752,225,167,155,12
4,1972-73 ...........................,4304,26.513815,3664,640,14.869888,2113,1888,225,196,181,15

In [17]:
df.tail()

,Unnamed: 0,Total,Unnamed: 2,Males,Females,Females as a percent of total,Total.1,Males.1,Females.1,Total.2,Males.2,Females.2
58,2017-18 ................,79598,11.456816,63704,15894,19.967838,46468,31397,15071,2017,1580,437
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Percent change,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,2007-08 to 2012-13 .........,32.287205,†,31.965586,33.789753,†,33.259242,32.142857,36.310044,8.07307,11.951589,-5.6
62,2012-13 to 2017-18 .........,56.193952,†,52.132588,74.909211,†,103.968045,89.836145,141.406375,9.97819,6.756757,23.446328

In [18]:
cs_df = df

## Other needed fixes
Identify other things that make this dataset not ideal to work with: Some of the headers got read in weirdly, for example with a '.1' or '.2' at the end, so changing this would make the data set would make it easier to work with. This would be needed to be fixed manually by looking at the original file. There are also some inconstencies in the empty values, like some of then are NaN and some of them are denoted by a '†'.